project:
  type: website
  output-dir: docs

website:
  title: "Jaslyn Miura"
  favicon: images/sakura2.png
  navbar:
    title: false
    logo: images/sakura2.png
    logo-alt: an drawing of an outline of a cherry blossom flower
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - href: posts.qmd
        text: posts
      - href: resources.qmd
        text: resources
      - icon: github
        href: https://github.com/jaslynmiura/jaslynmiura.github.io
  page-footer: 
    left: Copyright 2025, Jaslyn Miura
    right: 
      - icon: github
        href: https://github.com/jaslynmiura/jaslynmiura.github.io

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Raleway

editor: visual


